### ISSUE TITLE
2018.08.24 百度贴吧招前端开发

### ISSUE THREAD

**Issue by xtx1130** [xtx1130/blog#28]
由于最近公司里事情很多，一直没有冒泡，目前部门有两个空余前端hc。jd如下：
- js基础一定要好
- 熟悉vue全家桶
- 熟练html、css

加分项：  
- git上有开源项目贡献（非文档类）
- 深入理解node
- 熟悉或了解c++ addon

岗位信息： 

| 地点 | 级别 | 薪水 | rsu |
| ------ | ------ | ------ | ------ |
| 北京西二旗 | t4~t6 | 20k+面议 | t5+配给rsu |

**招聘截止之后会删除此贴，如果有兴趣请发邮件至xietianxin@baidu.com**

**Comment by xtx1130** [comment]
@liximomo 以后有机会的话可以合作，😆

**Comment by cdll** [comment]
魔都彩笔帮顶~

**Comment by xtx1130** [comment]
@cdll 来帝都么
